"""
METTL8 (AlphaFold) × Idebenone — Publication-grade docking analysis.
==================================================================
Receptor: METTL8 iso2 (UniProt Q9H825-2, AlphaFold AF-Q9H825-2-F1)
          Note: iso2 truncates the disordered N-terminus (res 2-51) and has
          higher mean pLDDT (77.9 vs 73.0). C-terminal methyltransferase
          domain is identical to iso1.
Ligand:   Idebenone (PubChem CID 3686, C19H30O5)
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from autodock import (
    compute_clash_score,
    detect_interactions,
    dock_ligand,
    find_top_pockets,
    post_process_docking,
    prepare_ligand,
    prepare_receptor,
    print_environment_status,
    validate_pose_with_posebusters,
)

OUTDIR = os.path.dirname(os.path.abspath(__file__))

# =========================================================================
# Step 0: Check environment
# =========================================================================
print_environment_status()
print()

# =========================================================================
# Step 1: Prepare receptor (AlphaFold → PDBQT with protonation fix)
# =========================================================================
ALPHAFOLD_CIF = os.path.join(OUTDIR, "AF-Q9H825-2-F1.cif")
RECEPTOR_PDBQT = os.path.join(OUTDIR, "METTL8_af_iso2.pdbqt")

if not os.path.exists(ALPHAFOLD_CIF):
    from autodock.fetchers import download_alphafold

    download_alphafold("Q9H825-2", OUTDIR, format="cif")

print("=" * 60)
print("Step 1: Preparing receptor (PDBFixer + reduce + PDB2PQR)")
print("=" * 60)

RECEPTOR_PDB = os.path.join(OUTDIR, "METTL8_af_iso2.pdb")

receptor_pdbqt = prepare_receptor(
    ALPHAFOLD_CIF,
    RECEPTOR_PDBQT,
    ph=7.4,
    remove_water=False,  # AlphaFold has no waters
    remove_hetatms=True,
    retain_metal_ions=True,
    predict_pka=True,  # report anomalous pKa
    fix_protonation=False,  # set True if pdb2pqr available
    force=True,  # overwrite existing
    detect_af_structure=True,  # auto pLDDT check
    output_pdb=RECEPTOR_PDB,  # save PDB for PLIP/PyMOL/PoseBusters
)
print(f"  Receptor PDBQT: {receptor_pdbqt}")
print()

# =========================================================================
# Step 2: Pocket detection (P2Rank + fpocket cross-validation)
# =========================================================================
print("=" * 60)
print("Step 2: Binding pocket detection")
print("=" * 60)

# Receptor PDB for PLIP/PyMOL — auto-generated by prepare_receptor(output_pdb=)
receptor_pdb = RECEPTOR_PDB

pockets = find_top_pockets(
    receptor_pdb,
    max_pockets=5,
    padding=5.0,
)
print(f"  Found {len(pockets)} pocket(s):")
for i, p in enumerate(pockets):
    drugg_score = p.get("druggability")
    drugg_str = (
        f"{drugg_score:.3f} ({p.get('druggability_level', 'N/A')})"
        if drugg_score is not None
        else str(p.get("druggability_level", "N/A"))
    )
    p2rank_val = p.get("p2rank_prob")
    p2rank_str = f"P2Rank={p2rank_val:.3f}" if p2rank_val is not None else "P2Rank=N/A"
    print(
        f"    #{i+1}: center={p['center']}, box={p['box_size']}, "
        f"druggability={drugg_str}, {p2rank_str}, "
        f"method={p.get('method', 'N/A')}"
    )
print()

# =========================================================================
# Step 3: Ligand source strategy — SMILES + multi-conformer
# =========================================================================
#
# Why SMILES-based conformer generation instead of PubChem SDF download:
#
# Idebenone has 12 rotatable bonds (C10 alkyl chain). A single pre-computed
# 3D conformer (from PubChem or any other source) captures only one low-energy
# state. The bioactive conformation in a protein pocket is often not the
# global energy minimum — it may be a higher-energy extended or folded state
# that the pocket stabilises.
#
# RDKit ETKDG (Experimental-Torsion Knowledge Distance Geometry) with the
# `multi_conformer=True` flag generates 10 diverse 3D conformers, docks each
# one independently, and returns the globally best pose across all conformers.
# This combines conformer pre-generation with Vina's flexible sampling
# (Riniker & Landrum 2015, JCIM).
#
# Key references:
#   - Riniker & Landrum (2015) "Better Informed Distance Geometry"
#   - Eberhardt et al. (2021) JCIM — multi-conformer docking best practice
#   - Hawkins (2017) "Conformer Generation with ETKDG" — J. Chem. Inf. Model.
# =========================================================================
print("=" * 60)
print("Step 3: Ligand preparation — SMILES + multi-conformer strategy")
print("=" * 60)

IDEBENONE_SMILES = "CC1=C(C(=O)C(=C(C1=O)OC)OC)CCCCCCCCCCO"

# Also prepare a single-conformer PDBQT for visualisation / fallback
LIGAND_PDBQT = os.path.join(OUTDIR, "idebenone.pdbqt")

# Single conformer (for reference / manual inspection)
prepare_ligand(
    IDEBENONE_SMILES,
    LIGAND_PDBQT,
    ph=7.4,
    name="IDE",
    molscrub_states=True,
    enumerate_stereo=False,
)
print(f"  Single-conformer PDBQT: {LIGAND_PDBQT}")
print("  Multi-conformer: 10 conformers via ETKDG (enabled in dock_ligand)")
print("  Strategy: dock each conformer independently, select globally best")
print()

# =========================================================================
# Step 4: Dock into each pocket (multi-conformer)
# =========================================================================
print("=" * 60)
print("Step 4: Multi-conformer docking × detected pockets")
print("=" * 60)

all_results = []
for i, pocket in enumerate(pockets):
    print(f"\n  ── Pocket #{i+1} ──")
    pocket_dir = os.path.join(OUTDIR, f"pocket_{i+1}")

    result = dock_ligand(
        receptor_pdbqt,
        LIGAND_PDBQT,  # single-conf PDBQT for API compat
        center=pocket["center"],
        box_size=pocket["box_size"],
        exhaustiveness=32,  # publication standard
        n_poses=20,
        seed=42,  # deterministic
        output_dir=pocket_dir,
        compound_name=f"IDE_pocket{i+1}",
        skip_consensus=False,  # include Vinardo consensus
        min_rmsd=1.0,
        auto_exhaustiveness=False,
        # NOTE: multi_conformer=True generates 10 conformers and docks each in
        # parallel spawn processes.  On machines with limited RAM (M1 8GB+),
        # 10 parallel Vina processes may cause OOM kills.  Default is single
        # conformer (robust); re-enable multi_conformer for higher thoroughness
        # on well-resourced machines.
        multi_conformer=False,  # set True for 10-conformer exhaustive search
        # ligand_smiles=IDEBENONE_SMILES,  # uncomment when multi_conformer=True
    )

    print(f"    Best affinity: {result.best_affinity:.2f} kcal/mol")
    if result.consensus_affinity:
        print(f"    Consensus (Vina+Vinardo): {result.consensus_affinity:.2f} kcal/mol")
    print(f"    N clusters: {result.n_clusters}")
    print(
        f"    Consensus conflict detection: "
        f"{'⚠️ bias detected' if result.all_scores.get('vinardo_best_pose_idx', 0) > 0 else '✅ Vina/Vinardo agree'}"
    )

    all_results.append(result)

# =========================================================================
# Step 5: Rank pockets by best affinity
# =========================================================================
print("\n" + "=" * 60)
print("Step 5: Pocket ranking by affinity")
print("=" * 60)

ranked = sorted(
    [(r, i) for i, r in enumerate(all_results) if r.best_affinity is not None],
    key=lambda x: x[0].best_affinity,
)
for rank, (r, idx) in enumerate(ranked, 1):
    p = pockets[idx]
    drugg = p.get("druggability")
    drugg_str = f"{drugg:.3f}" if drugg is not None else "N/A"
    p2rank = p.get("p2rank_prob")
    p2rank_str = f"{p2rank:.3f}" if p2rank is not None else "N/A"
    print(
        f"  #{rank}: Pocket #{idx+1} — {r.best_affinity:.2f} kcal/mol "
        f"(consensus: {r.consensus_affinity or 'N/A'}) "
        f"[P2Rank={p2rank_str}, drugg={drugg_str}]"
    )

if ranked:
    best = ranked[0]
    best_p = pockets[best[1]]
    best_drugg = best_p.get("druggability")
    best_drugg_str = (
        f"{best_drugg:.3f} ({best_p.get('druggability_level', 'N/A')})"
        if best_drugg is not None
        else best_p.get("druggability_level", "N/A")
    )
    print(
        f"\n  🏆 Best pocket: #{best[1]+1} ({best[0].best_affinity:.2f} kcal/mol, "
        f"druggability={best_drugg_str})"
    )
    print()

# =========================================================================
# Step 6: Post-processing (interactions + validation + report)
# =========================================================================
if ranked:
    best_result, best_idx = ranked[0]
    best_pocket_dir = os.path.join(OUTDIR, f"pocket_{best_idx+1}")
    best_pose_path = best_result.best_pose_pdbqt

    print("=" * 60)
    print("Step 6: Post-processing (best pose)")
    print("=" * 60)

    # Interaction detection (PLIP)
    try:
        interactions = detect_interactions(
            receptor_pdb,
            best_pose_path,
            method="plip",
        )
        best_result.interactions = interactions
        print(f"  PLIP interactions detected: {len(interactions)}")
        # Summary
        from collections import Counter

        type_counts = Counter(i.get("type", "Unknown") for i in interactions)
        for itype, cnt in sorted(type_counts.items()):
            print(f"    {itype}: {cnt}")
    except Exception as e:
        print(f"  Interaction detection skipped: {e}")

    # Clash detection
    try:
        clash = compute_clash_score(best_pose_path, receptor_pdb)
        print(
            f"  Clash score: {clash.get('clash_score', 'N/A')} Å "
            f"(acceptable: {clash.get('is_acceptable', 'N/A')})"
        )
    except Exception as e:
        print(f"  Clash detection skipped: {e}")

    # PoseBusters validation
    try:
        pb = validate_pose_with_posebusters(best_pose_path, receptor_pdb)
        print(
            f"  PoseBusters: {'PASS' if pb.get('pass') else 'FAIL'} "
            f"(available: {pb.get('available', False)})"
        )
    except Exception as e:
        print(f"  PoseBusters skipped: {e}")

    # Full pipeline post-processing
    print("\n  Generating publication-ready output...")
    outputs = post_process_docking(
        best_result,
        os.path.join(OUTDIR, "best_result"),
        receptor_pdb=receptor_pdb,
        do_interactions=True,
        do_rendering=True,
        do_report=True,
    )

    print(f"\n  📄 Report: {outputs.get('pdf', 'N/A')}")
    print(f"  📊 CSV:    {outputs.get('csv', 'N/A')}")
    print(f"  🖼️  Figures: {outputs.get('figures', [])}")

# =========================================================================
# Step 7: Save all results to JSON
# =========================================================================
summary = {
    "receptor": "METTL8 iso2 (AlphaFold Q9H825-2, pLDDT=77.9)",
    "ligand": "Idebenone (CID 3686, C19H30O5, 12 rotatable bonds)",
    "ligand_strategy": "SMILES → RDKit ETKDG → 10 conformers, docked independently",
    "docking_params": {"exhaustiveness": 32, "n_poses": 20, "seed": 42},
    "pockets": pockets,
    "results": [r.to_dict() for r in all_results],
}
with open(os.path.join(OUTDIR, "docking_summary.json"), "w") as f:
    json.dump(summary, f, indent=2, default=str)

print("\n" + "=" * 60)
print("✅ Docking complete!")
print(f"   Summary: {os.path.join(OUTDIR, 'docking_summary.json')}")
print("=" * 60)
